name: Update Parsers

on:
  schedule:
    - cron: '30 0 15 * *'

jobs:
  update-parsers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tier: 1
            reviewers: ''
          - tier: 2
            reviewers: 'Decodetalkers,tunaflsh,romus204'
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action@v2
        with:
          install-lib: false

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.4.1
          args: false

      - name: Update parsers
        run: ./scripts/nvim/update-parsers.lua --tier=${{ matrix.tier }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: lua/tree-sitter-manager/repos.lua
          token: ${{ secrets.GITHUB_TOKEN }}
          sign-commits: true
          commit-message: "ops(parsers): update ${{ env.UPDATED_PARSERS }}"
          branch: update-parsers-tier-${{ matrix.tier }}
          delete-branch: true
          title: Update Parsers Tier ${{ matrix.tier }}
          body: Update ${{ env.UPDATED_PARSERS }}
          labels: |
            automated pr
            auto update
          assignees: tunaflsh
          reviewers: ${{ matrix.reviewers }}

      - name: Auto-Merge Tier 2
        if: ${{ matrix.tier == 2 && steps.cpr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --auto --squash
