name: Quality Control

on:
  pull_request:
    branches: [ "main", "develop" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stylua:
    name: Stylua Check
    if: "!startsWith(github.head_ref, 'update-parsers-tier-')"
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.4.1
          args: --check .

  detect-changes:
    name: Detect Changes
    if: "!startsWith(github.head_ref, 'update-parsers-tier-')"
    runs-on: ubuntu-slim
    continue-on-error: true
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'lua/**'
              - 'tests/**'
              - 'scripts/nvim/init.lua'

  test:
    name: Run Tests
    needs: [stylua, detect-changes]
    if: |
      always() &&
      !startsWith(github.head_ref, 'update-parsers-tier-') &&
      needs.stylua.result == 'success' &&
      (needs.detect-changes.outputs.code == 'true' ||
       needs.detect-changes.result == 'failure')
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v4

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action@v2
        with:
          install-lib: false

      - name: Run tests
        run: make test

  test-parsers:
    name: Test Updated Parsers
    if: startsWith(github.head_ref, 'update-parsers-tier-')
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v4

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action@v2
        with:
          install-lib: false

      - name: Run tests
        env:
          UPDATED_PARSERS: ${{ github.event.pull_request.body }}
        run: make test_all_queries $UPDATED_PARSERS
